Repository vanmxpx/ISDPlatform, pull requests merged in 2019-09, with the labels that each got.

#201 Added canDeactivate feature to game page
  Cooper/ClientApp/src.v2/app/app-routing.module.ts
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/guards/exit.guard.ts
  Cooper/ClientApp/src.v2/app/guards/index.ts
  Cooper/ClientApp/src.v2/app/layouts/game/game.layout.ts
  Cooper/ClientApp/tslint.json
Labels: feature, front-end

#203 #157 Transactions in UsersConnectionsDAO
  Cooper.Controllers/UsersConnectionController.cs
  Cooper.DAO/UsersConnectionDAO/UsersConnectionDAO.cs
  Cooper.ORM/DbTools.cs
Labels: back-end, refactoring

#205 Add new checks to githooks
  .githooks/pre-push
  Cooper.Tests/ORM/DbToolsTest.cs
Labels: 3 minutes task, low

#192 #186 Mediaserver for Cooper
  Cooper.Controllers/MediaserverController.cs
  Cooper.DAO/UserDAO/IUserDAO.cs
  Cooper.DAO/UserDAO/UserDAO.cs
  Cooper.Repositories/User/IUserRepository.cs
  Cooper.Repositories/User/UserRepository.cs
  Cooper.Services.Interfaces/Cooper.Services.Interfaces.csproj
  Cooper.Services.Interfaces/IConfigProvider.cs
  Cooper.Services.Interfaces/IMediaserver.cs
  Cooper.Services.Interfaces/IMediaserverConf.cs
  Cooper.Services/ConfigurationService/ConfigLoader.cs
  Cooper.Services/ConfigurationService/ConfigProvider.cs
  Cooper.Services/ConfigurationService/Configuration/Models/MediaserverConf.cs
  Cooper.Services/MediaserverService/MediaserverService.cs
  Cooper.Services/MediaserverService/MediaserverServiceExtension.cs
  Cooper.Services/SocialAuthService/SocialAuth.cs
  Cooper/ClientApp/package-lock.json
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/components/avatar-card/avatar-card.component.scss
  Cooper/ClientApp/src.v2/app/components/index.ts
  Cooper/ClientApp/src.v2/app/components/upload-form/upload-form.component.html
  Cooper/ClientApp/src.v2/app/components/upload-form/upload-form.component.scss
  Cooper/ClientApp/src.v2/app/components/upload-form/upload-form.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/upload-form/upload-form.component.ts
  Cooper/ClientApp/src.v2/app/layouts/index.ts
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.html
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/upload-form/upload-form.layout.html
  Cooper/ClientApp/src.v2/app/layouts/upload-form/upload-form.layout.scss
  Cooper/ClientApp/src.v2/app/layouts/upload-form/upload-form.layout.spec.ts
  Cooper/ClientApp/src.v2/app/layouts/upload-form/upload-form.layout.ts
  Cooper/ClientApp/src.v2/app/services/index.ts
  Cooper/ClientApp/src.v2/app/services/mediaserver/mediaserver.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/mediaserver/mediaserver.service.ts
  Cooper/Startup.cs
  Cooper/appsettings.json
  Tools/MediaServer/MediaServer/MediaServer/Startup.cs
  Tools/MediaServer/MediaServer/MediaServer/wwwroot/Images/.keep
Labels: back-end, feature, front-end

#210 #207 Log out button enabled
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.html
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.ts
Labels: 3 minutes task, front-end

#199 Temporary home page lookout
  Cooper/ClientApp/src.v2/app/layouts/home/home.layout.html
  Cooper/ClientApp/src.v2/app/layouts/home/home.layout.scss
  Cooper/ClientApp/src.v2/assets/imageKeeper/house-repair.png
Labels: front-end

#200 Bug with routes on profile page fixed
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.ts
Labels: bug, front-end

#206 Refactor generation "where"
  Cooper.DAO/ChatDAO.cs
  Cooper.DAO/GameDAO.cs
  Cooper.DAO/GameReviewDAO.cs
  Cooper.DAO/GameStatisticsDAO.cs
  Cooper.DAO/MessageDAO.cs
  Cooper.DAO/UserDAO/UserDAO.cs
  Cooper.DAO/UserReviewDAO.cs
  Cooper.DAO/UsersConnectionDAO/UsersConnectionDAO.cs
  Cooper.DAO/VerificationDAO.cs
  Cooper.ORM/CRUD.cs
  Cooper.ORM/DbTools.cs
  Cooper.ORM/ICRUD.cs
  Cooper.ORM/Operators.cs
  Cooper.ORM/WhereRequest.cs
  Cooper.Repositories/UsersConnection/UsersConnectionRepository.cs
  Cooper.Services/JwtHandlerService/JwtHandlerService.cs
  Cooper.Services/JwtHandlerService/JwtHandlerServiceExtension.cs
  Cooper.Services/TokenCleanerService/TokenCleaner.cs
  Cooper.Services/UsersConnectionService/UsersConnectionService.cs
  Cooper.Services/UsersConnectionService/UsersConnectionServiceExtension.cs
  Cooper.Tests/ORM/DbToolsTest.cs
Labels: back-end, refactoring

#160 Translations on frontend(t#106)
  Cooper/ClientApp/package-lock.json
  Cooper/ClientApp/package.json
  Cooper/ClientApp/src.v2/app/app.component.ts
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/components/game-card/game-card.component.html
  Cooper/ClientApp/src.v2/app/components/game-card/game-card.component.ts
  Cooper/ClientApp/src.v2/app/components/game-list-item/game-list-item.component.html
  Cooper/ClientApp/src.v2/app/components/index.ts
  Cooper/ClientApp/src.v2/app/components/language-select/language-select.component.html
  Cooper/ClientApp/src.v2/app/components/language-select/language-select.component.scss
  Cooper/ClientApp/src.v2/app/components/language-select/language-select.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/language-select/language-select.component.ts
  Cooper/ClientApp/src.v2/app/components/login-form/login-form.component.css
  Cooper/ClientApp/src.v2/app/components/login-form/login-form.component.html
  Cooper/ClientApp/src.v2/app/components/login-form/login-form.component.ts
  Cooper/ClientApp/src.v2/app/components/navigation/navigation.component.html
  Cooper/ClientApp/src.v2/app/components/navigation/navigation.component.ts
  Cooper/ClientApp/src.v2/app/enums/Languages.ts
  Cooper/ClientApp/src.v2/app/enums/index.ts
  Cooper/ClientApp/src.v2/app/guards/auth-guard.ts
  Cooper/ClientApp/src.v2/app/helpers/index.ts
  Cooper/ClientApp/src.v2/app/helpers/languages.helper.ts
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.html
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/login/login.layout.html
  Cooper/ClientApp/src.v2/app/layouts/login/login.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/platform/platform.layout.scss
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.html
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.scss
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.ts
  Cooper/ClientApp/src.v2/app/pipes/index.ts
  Cooper/ClientApp/src.v2/app/pipes/language-name-pipe/language-name.pipe.spec.ts
  Cooper/ClientApp/src.v2/app/pipes/language-name-pipe/language-name.pipe.ts
  Cooper/ClientApp/src.v2/app/services/games/games.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/games/games.service.ts
  Cooper/ClientApp/src.v2/app/services/index.ts
  Cooper/ClientApp/src.v2/app/services/interceptor/cooper.interceptor.ts
  Cooper/ClientApp/src.v2/app/services/language-storage/language-storage.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/localization/localization.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/localization/localization.service.ts
  Cooper/ClientApp/src.v2/app/services/session/session.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/session/session.service.ts
  Cooper/ClientApp/src.v2/app/services/user/user.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/user/user.service.ts
  Cooper/ClientApp/src.v2/app/services/users-iteration/users-interaction.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/users-iteration/users-interaction.service.ts
  Cooper/ClientApp/src.v2/assets/i18n/en.json
  Cooper/ClientApp/src.v2/assets/i18n/ru.json
  Cooper/ClientApp/src.v2/assets/i18n/ua.json
  Cooper/ClientApp/src/app/animations/route-animation.ts
  Cooper/ClientApp/src/app/components/auth/guards/auth-guard.ts
  Cooper/ClientApp/src/app/components/games/games.component.css
  Cooper/ClientApp/src/app/components/games/games.component.html
  Cooper/ClientApp/src/app/pipes/safe.pipe.ts
  Cooper/ClientApp/src/assets/cooper.interceptor.ts
  Documentation/Database/InsertBasicInfo.Sql
Labels: development, feature, front-end
