Repository vanmxpx/ISDPlatform, pull requests merged in 2019-07, with the labels that each got.

#88 User connections issue
  Cooper/Controllers/UsersConnectionController.cs
  Cooper/DAO/Mapping/EntityMapping.cs
  Cooper/DAO/UsersConnectionDAO/UsersConnectionDAO.cs
  Cooper/ORM/DBTools.cs
  Cooper/Repository/UsersConnection/ConnectionType.cs
Labels: back-end

#97 #96 Refactoring/JwtHandlerService
  Cooper/Services/JwtHandlerService/JwtHandlerService.cs
  Cooper/Services/JwtHandlerService/JwtHandlerServiceExtension.cs
Labels: back-end, refactoring

#90 Oracle Database Updater
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/ConsoleCommands/ConsoleCommandManual.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/ConsoleCommands/ConsoleCommandRegistry.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/ConsoleCommands/ExitCommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/ConsoleCommands/HelpCommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/ConsoleCommands/Interfaces/ICommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/ConsoleCommands/UpdateCommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/ConsoleCommands/VersionCommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/ConsoleCommands/VersionsCommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/Interfaces/ICommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/Interfaces/IExecutable.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/SQLCommands/AlterCommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/SQLCommands/BaseCommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/SQLCommands/CreateCommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/SQLCommands/DeleteCommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/SQLCommands/DropCommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/SQLCommands/InsertCommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/SQLCommands/Interfaces/ICommand.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Commands/SQLCommands/QueryExecutor.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Configuration.cs
  Tools/OracleDBUpdater/OracleDBUpdater/MyDataBase.cs
  Tools/OracleDBUpdater/OracleDBUpdater/Program.cs
  Tools/OracleDBUpdater/OracleDBUpdater/VersionHandler.cs
Labels: back-end

#107 Client/refactoring: game
  .vscode/launch.json
  Cooper/ClientApp/angular.json
  Cooper/ClientApp/proxy.conf.json
  Cooper/ClientApp/src/app/app-routing.module.ts
  Cooper/ClientApp/src/app/app.module.ts
  Cooper/ClientApp/src/app/components/games/games.component.css
  Cooper/ClientApp/src/app/components/games/games.component.html
  Cooper/ClientApp/src/app/components/games/games.component.ts
  Cooper/ClientApp/src/app/components/home/game/game.component.css
  Cooper/ClientApp/src/app/components/home/game/game.component.html
  Cooper/ClientApp/src/app/components/home/game/game.component.spec.ts
  Cooper/ClientApp/src/app/components/home/game/game.component.ts
  Cooper/ClientApp/src/app/components/home/home.component.css
  Cooper/ClientApp/src/app/components/home/home.component.html
  Cooper/ClientApp/src/app/components/home/home.component.ts
  Cooper/ClientApp/src/app/models/game.ts
  Cooper/ClientApp/src/assets/imageKeeper/IslandsLogo.ico
  Cooper/ClientApp/src/assets/imageKeeper/gamepad.jpeg
  Cooper/ClientApp/src/styles.css
  Cooper/Controllers/ProxyController.cs
  Cooper/Cooper.csproj
  Cooper/Startup.cs
  Documentation/Database/UpdateScript_v1.3.Sql
Labels: front-end, refactoring

#99 Client/refactoring/registration
  Cooper/ClientApp/src/app/components/auth/sign-in/sign-in.component.ts
  Cooper/ClientApp/src/app/components/auth/sign-up/sign-up.component.html
  Cooper/ClientApp/src/app/components/auth/sign-up/sign-up.component.ts
  Cooper/ClientApp/src/app/services/registration/registration.service.spec.ts
  Cooper/ClientApp/src/app/services/registration/registration.service.ts
  Cooper/ClientApp/src/app/services/user.service.ts
Labels: front-end, refactoring

#100 Client/feature: Service for users interection
  Cooper/ClientApp/src/app/models/user.ts
  Cooper/ClientApp/src/app/services/users/users-interaction.service.spec.ts
  Cooper/ClientApp/src/app/services/users/users-interaction.service.ts
Labels: feature, front-end

#117 Client/architecture/refactoring/new structure
  Cooper/ClientApp/src.v2/app/app-routing.module.ts
  Cooper/ClientApp/src.v2/app/app.component.css
  Cooper/ClientApp/src.v2/app/app.component.html
  Cooper/ClientApp/src.v2/app/app.component.spec.ts
  Cooper/ClientApp/src.v2/app/app.component.ts
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/components/index.ts
  Cooper/ClientApp/src.v2/app/helpers/index.ts
  Cooper/ClientApp/src.v2/app/layouts/index.ts
  Cooper/ClientApp/src.v2/app/models/index.ts
  Cooper/ClientApp/src.v2/app/pipes/index.ts
  Cooper/ClientApp/src.v2/app/services/index.ts
  Cooper/ClientApp/src.v2/assets/.gitkeep
  Cooper/ClientApp/src.v2/assets/cooper.interceptor.ts
  Cooper/ClientApp/src.v2/assets/imageKeeper/111.ico
  Cooper/ClientApp/src.v2/assets/imageKeeper/111.png
  Cooper/ClientApp/src.v2/assets/imageKeeper/Cooper3.jpg
  Cooper/ClientApp/src.v2/assets/imageKeeper/CooperNoBack.png
  Cooper/ClientApp/src.v2/assets/imageKeeper/IslandsLogo.ico
  Cooper/ClientApp/src.v2/assets/imageKeeper/PlayStat.png
  Cooper/ClientApp/src.v2/assets/imageKeeper/WebTanks.png
  Cooper/ClientApp/src.v2/assets/imageKeeper/exit.png
  Cooper/ClientApp/src.v2/assets/imageKeeper/facebook-icon.png
  Cooper/ClientApp/src.v2/assets/imageKeeper/gamepad.jpeg
  Cooper/ClientApp/src.v2/assets/imageKeeper/google-icon.png
  Cooper/ClientApp/src.v2/assets/imageKeeper/postversand.png
  Cooper/ClientApp/src.v2/assets/imageKeeper/robot.png
  Cooper/ClientApp/src.v2/browserslist
  Cooper/ClientApp/src.v2/environments/environment.prod.ts
  Cooper/ClientApp/src.v2/environments/environment.ts
  Cooper/ClientApp/src.v2/favicon.ico
  Cooper/ClientApp/src.v2/index.html
  Cooper/ClientApp/src.v2/karma.conf.js
  Cooper/ClientApp/src.v2/main.ts
  Cooper/ClientApp/src.v2/polyfills.ts
  Cooper/ClientApp/src.v2/styles.css
  Cooper/ClientApp/src.v2/test.ts
  Cooper/ClientApp/src.v2/tsconfig.app.json
  Cooper/ClientApp/src.v2/tsconfig.server.json
  Cooper/ClientApp/src.v2/tsconfig.spec.json
  Cooper/ClientApp/src.v2/tslint.json
Labels: front-end, refactoring

#127 Client/architecture/refactoring: Main components added (#122 issue)
  Cooper/ClientApp/angular.json
  Cooper/ClientApp/src.v2/app/app-routing.module.ts
  Cooper/ClientApp/src.v2/app/app.component.ts
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/components/index.ts
  Cooper/ClientApp/src.v2/app/components/login/login.component.css
  Cooper/ClientApp/src.v2/app/components/login/login.component.html
  Cooper/ClientApp/src.v2/app/components/login/login.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/login/login.component.ts
  Cooper/ClientApp/src.v2/app/components/registration/registration.component.css
  Cooper/ClientApp/src.v2/app/components/registration/registration.component.html
  Cooper/ClientApp/src.v2/app/components/registration/registration.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/registration/registration.component.ts
  Cooper/ClientApp/src.v2/app/layouts/game/game.layout.css
  Cooper/ClientApp/src.v2/app/layouts/game/game.layout.html
  Cooper/ClientApp/src.v2/app/layouts/game/game.layout.spec.ts
  Cooper/ClientApp/src.v2/app/layouts/game/game.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.css
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.html
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.spec.ts
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/index.ts
  Cooper/ClientApp/src.v2/app/layouts/login/login.layout.css
  Cooper/ClientApp/src.v2/app/layouts/login/login.layout.html
  Cooper/ClientApp/src.v2/app/layouts/login/login.layout.spec.ts
  Cooper/ClientApp/src.v2/app/layouts/login/login.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/platform/platform.layout.css
  Cooper/ClientApp/src.v2/app/layouts/platform/platform.layout.html
  Cooper/ClientApp/src.v2/app/layouts/platform/platform.layout.spec.ts
  Cooper/ClientApp/src.v2/app/layouts/platform/platform.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.css
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.html
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.spec.ts
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/registration/registration.layout.css
  Cooper/ClientApp/src.v2/app/layouts/registration/registration.layout.html
  Cooper/ClientApp/src.v2/app/layouts/registration/registration.layout.spec.ts
  Cooper/ClientApp/src.v2/app/layouts/registration/registration.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.css
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.html
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.spec.ts
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.ts
  Cooper/ClientApp/src.v2/index.html
  Cooper/ClientApp/src.v2/tslint.json
Labels: front-end, refactoring

#121 Add description field for user on backend
  Cooper/DAO/Mapping/EntityMapping.cs
  Cooper/DAO/Models/UserDb.cs
  Cooper/DAO/UserDAO/UserDAO.cs
  Cooper/Models/User.cs
  Cooper/Repository/Mapping/ModelsMapper.cs
  Cooper/Repository/User/UserRepository.cs
Labels: back-end, feature

#128 Tunning routing (Issue #122)
  Cooper/ClientApp/src.v2/app/app-routing.module.ts
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/layouts/index.ts
  Cooper/ClientApp/src.v2/app/layouts/page-not-found/page-not-found.layout.css
  Cooper/ClientApp/src.v2/app/layouts/page-not-found/page-not-found.layout.html
  Cooper/ClientApp/src.v2/app/layouts/page-not-found/page-not-found.layout.spec.ts
  Cooper/ClientApp/src.v2/app/layouts/page-not-found/page-not-found.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/platform/platform.layout.html
Labels: front-end, refactoring

#120 Adding stability to SocAuth service
  Cooper/Services/SocialAuthService/SocialAuth.cs
Labels: back-end

#133 Add documentation for the media server
  Tools/MediaServer/Documentation/README.md
  Tools/MediaServer/MediaServer/MediaServer.Tests/ImageRepositoryTest.cs
  Tools/MediaServer/MediaServer/MediaServer.Tests/MediaServer.Tests.csproj
  Tools/MediaServer/MediaServer/MediaServer.Tests/Properties/Resources.Designer.cs
  Tools/MediaServer/MediaServer/MediaServer.Tests/Properties/Resources.resx
  Tools/MediaServer/MediaServer/MediaServer.Tests/Resources/default.jpg
  Tools/MediaServer/MediaServer/MediaServer.sln
  Tools/MediaServer/MediaServer/MediaServer/Controllers/ImageController.cs
  Tools/MediaServer/MediaServer/MediaServer/MediaServer.csproj
  Tools/MediaServer/MediaServer/MediaServer/Models/ErrorModel.cs
  Tools/MediaServer/MediaServer/MediaServer/Models/ImageModel.cs
  Tools/MediaServer/MediaServer/MediaServer/Program.cs
  Tools/MediaServer/MediaServer/MediaServer/Services/IImageRepository.cs
  Tools/MediaServer/MediaServer/MediaServer/Services/ImageRepository.cs
  Tools/MediaServer/MediaServer/MediaServer/Services/MockImageRepository.cs
  Tools/MediaServer/MediaServer/MediaServer/Startup.cs
  Tools/MediaServer/MediaServer/MediaServer/appsettings.Development.json
  Tools/MediaServer/MediaServer/MediaServer/appsettings.json
  Tools/MediaServer/MediaServer/MediaServer/wwwroot/favicon.ico
  Tools/MediaServer/MediaServer/Utility.Tests/ImageHelperTests.cs
  Tools/MediaServer/MediaServer/Utility.Tests/Properties/Resources.Designer.cs
  Tools/MediaServer/MediaServer/Utility.Tests/Properties/Resources.resx
  Tools/MediaServer/MediaServer/Utility.Tests/Resources/TestImage.jpg
  Tools/MediaServer/MediaServer/Utility.Tests/Utility.Tests.csproj
  Tools/MediaServer/MediaServer/Utility/FromFileHelper.cs
  Tools/MediaServer/MediaServer/Utility/ImageHelper.cs
  Tools/MediaServer/MediaServer/Utility/Utility.csproj
  Tools/MediaServer/MediaServer/Views/Image/Index.cshtml
  Tools/MediaServer/MediaServer/Views/_ViewImports.cshtml
  Tools/MediaServer/MediaServer/wwwroot/Images/default.jpg
Labels: back-end

#134 Folder path, login page, separate service (#108, #122, #132)
  Cooper/ClientApp/src.v2/app/app-routing.module.ts
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/components/index.ts
  Cooper/ClientApp/src.v2/app/components/login-form/login-form.component.css
  Cooper/ClientApp/src.v2/app/components/login-form/login-form.component.html
  Cooper/ClientApp/src.v2/app/components/login-form/login-form.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/login-form/login-form.component.ts
  Cooper/ClientApp/src.v2/app/components/login/login.component.html
  Cooper/ClientApp/src.v2/app/components/login/login.component.ts
  Cooper/ClientApp/src.v2/app/components/poster/poster.component.css
  Cooper/ClientApp/src.v2/app/components/poster/poster.component.html
  Cooper/ClientApp/src.v2/app/components/poster/poster.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/poster/poster.component.ts
  Cooper/ClientApp/src.v2/app/components/registration-form/registration-form.component.css
  Cooper/ClientApp/src.v2/app/components/registration-form/registration-form.component.html
  Cooper/ClientApp/src.v2/app/components/registration-form/registration-form.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/registration-form/registration-form.component.ts
  Cooper/ClientApp/src.v2/app/components/registration/registration.component.css
  Cooper/ClientApp/src.v2/app/components/registration/registration.component.ts
  Cooper/ClientApp/src.v2/app/enums/SocialNetwork.ts
  Cooper/ClientApp/src.v2/app/enums/index.ts
  Cooper/ClientApp/src.v2/app/guards/auth-guard.ts
  Cooper/ClientApp/src.v2/app/guards/index.ts
  Cooper/ClientApp/src.v2/app/layouts/index.ts
  Cooper/ClientApp/src.v2/app/layouts/login/login.layout.css
  Cooper/ClientApp/src.v2/app/layouts/login/login.layout.html
  Cooper/ClientApp/src.v2/app/layouts/login/login.layout.ts
  Cooper/ClientApp/src.v2/app/services/authentification/authentification.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/authentification/authentification.service.ts
  Cooper/ClientApp/src.v2/app/services/index.ts
  Cooper/ClientApp/src.v2/styles.css
  Cooper/ClientApp/tsconfig.json
Labels: front-end, refactoring

#141 Issue #125 : Games component in src.v2
  Cooper/ClientApp/angular.json
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/components/game-card/game-card.component.html
  Cooper/ClientApp/src.v2/app/components/game-card/game-card.component.scss
  Cooper/ClientApp/src.v2/app/components/game-card/game-card.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/game-card/game-card.component.ts
  Cooper/ClientApp/src.v2/app/components/game-list-item/game-list-item.component.html
  Cooper/ClientApp/src.v2/app/components/game-list-item/game-list-item.component.scss
  Cooper/ClientApp/src.v2/app/components/game-list-item/game-list-item.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/game-list-item/game-list-item.component.ts
  Cooper/ClientApp/src.v2/app/components/index.ts
  Cooper/ClientApp/src.v2/app/enums/GameListTabs.ts
  Cooper/ClientApp/src.v2/app/enums/index.ts
  Cooper/ClientApp/src.v2/app/helpers/animation.helper.ts
  Cooper/ClientApp/src.v2/app/helpers/index.ts
  Cooper/ClientApp/src.v2/app/layouts/game/game.layout.html
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.css
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.html
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.scss
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.ts
  Cooper/ClientApp/src.v2/app/models/game-model.ts
  Cooper/ClientApp/src.v2/app/models/index.ts
  Cooper/ClientApp/src.v2/app/services/games.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/games.service.ts
  Cooper/ClientApp/src.v2/app/services/index.ts
Labels: feature, front-end, technical

#144 Fix tests error for Media Server
  Tools/MediaServer/MediaServer/MediaServer.Tests/ImageRepositoryTest.cs
  Tools/MediaServer/MediaServer/MediaServer.Tests/MediaServer.Tests.csproj
  Tools/MediaServer/MediaServer/MediaServer.Tests/Properties/Resources.Designer.cs
  Tools/MediaServer/MediaServer/MediaServer.Tests/Properties/Resources.resx
  Tools/MediaServer/MediaServer/MediaServer.Tests/Resources/default.jpg
  Tools/MediaServer/MediaServer/Utility.Tests/ImageHelperTests.cs
  Tools/MediaServer/MediaServer/Utility.Tests/Properties/Resources.Designer.cs
  Tools/MediaServer/MediaServer/Utility.Tests/Properties/Resources.resx
  Tools/MediaServer/MediaServer/Utility.Tests/Resources/TestImage.jpg
  Tools/MediaServer/MediaServer/Utility/ImageHelper.cs
Labels: back-end, bug

#136 Top panel was added with navigation component
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/components/index.ts
  Cooper/ClientApp/src.v2/app/components/navigation/navigation.component.html
  Cooper/ClientApp/src.v2/app/components/navigation/navigation.component.scss
  Cooper/ClientApp/src.v2/app/components/navigation/navigation.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/navigation/navigation.component.ts
  Cooper/ClientApp/src.v2/app/constants.scss
  Cooper/ClientApp/src.v2/app/layouts/platform/platform.layout.css
  Cooper/ClientApp/src.v2/app/layouts/platform/platform.layout.html
  Cooper/ClientApp/src.v2/app/layouts/platform/platform.layout.scss
  Cooper/ClientApp/src.v2/app/layouts/platform/platform.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.css
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.html
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.scss
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.ts
  Cooper/ClientApp/src.v2/app/models/coop-navbar-item.ts
  Cooper/ClientApp/src.v2/app/models/index.ts
Labels: front-end

#146 Fix incorrect hash generation
  Tools/MediaServer/MediaServer/MediaServer.Tests/ImageRepositoryTest.cs
  Tools/MediaServer/MediaServer/MediaServer.Tests/MediaServer.Tests.csproj
  Tools/MediaServer/MediaServer/MediaServer/Controllers/ImageController.cs
  Tools/MediaServer/MediaServer/MediaServer/MediaServer.csproj
  Tools/MediaServer/MediaServer/MediaServer/Services/IImageRepository.cs
  Tools/MediaServer/MediaServer/MediaServer/Services/ImageRepository.cs
  Tools/MediaServer/MediaServer/MediaServer/Services/MockImageRepository.cs
  Tools/MediaServer/MediaServer/MediaServer/Startup.cs
  Tools/MediaServer/MediaServer/Utility.Tests/ImageHelperTests.cs
  Tools/MediaServer/MediaServer/Utility.Tests/Utility.Tests.csproj
  Tools/MediaServer/MediaServer/Utility/FromFileHelper.cs
  Tools/MediaServer/MediaServer/Utility/ImageHelper.cs
  Tools/MediaServer/MediaServer/Utility/Utility.csproj
Labels: back-end, bug
