Repository vanmxpx/ISDPlatform, pull requests merged in 2019-08, with the labels that each got.

#150 Swagger for the media server
  Tools/MediaServer/MediaServer/MediaServer/Controllers/ImageController.cs
  Tools/MediaServer/MediaServer/MediaServer/MediaServer.csproj
  Tools/MediaServer/MediaServer/MediaServer/Startup.cs
Labels: back-end, feature

#153 Swagger for the Cooper
  Cooper/Controllers/AuthController.cs
  Cooper/Controllers/ChatController.cs
  Cooper/Controllers/CommonMessageController.cs
  Cooper/Controllers/ConfirmationEmailController.cs
  Cooper/Controllers/GameController.cs
  Cooper/Controllers/GameReviewController.cs
  Cooper/Controllers/GameStatisticsController.cs
  Cooper/Controllers/MessageController.cs
  Cooper/Controllers/RegistrationController.cs
  Cooper/Controllers/UserController.cs
  Cooper/Controllers/UserReviewController.cs
  Cooper/Controllers/UsersConnectionController.cs
  Cooper/Cooper.csproj
  Cooper/Startup.cs
Labels: back-end, feature

#161 Fix confirmation email controller
  Cooper.Controllers/ConfirmationEmailController.cs
Labels: back-end, bug, high

#156 Client/refactoring/architecture/profile
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/components/avatar-card/avatar-card.component.html
  Cooper/ClientApp/src.v2/app/components/avatar-card/avatar-card.component.scss
  Cooper/ClientApp/src.v2/app/components/avatar-card/avatar-card.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/avatar-card/avatar-card.component.ts
  Cooper/ClientApp/src.v2/app/components/games-list/games-list.component.css
  Cooper/ClientApp/src.v2/app/components/games-list/games-list.component.html
  Cooper/ClientApp/src.v2/app/components/games-list/games-list.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/games-list/games-list.component.ts
  Cooper/ClientApp/src.v2/app/components/index.ts
  Cooper/ClientApp/src.v2/app/components/my-profile/my-profile.component.css
  Cooper/ClientApp/src.v2/app/components/my-profile/my-profile.component.html
  Cooper/ClientApp/src.v2/app/components/my-profile/my-profile.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/my-profile/my-profile.component.ts
  Cooper/ClientApp/src.v2/app/components/user-connections-list/user-connections-list.component.css
  Cooper/ClientApp/src.v2/app/components/user-connections-list/user-connections-list.component.html
  Cooper/ClientApp/src.v2/app/components/user-connections-list/user-connections-list.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/user-connections-list/user-connections-list.component.ts
  Cooper/ClientApp/src.v2/app/components/user-info/user-info.component.css
  Cooper/ClientApp/src.v2/app/components/user-info/user-info.component.html
  Cooper/ClientApp/src.v2/app/components/user-info/user-info.component.spec.ts
  Cooper/ClientApp/src.v2/app/components/user-info/user-info.component.ts
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.html
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.ts
  Cooper/ClientApp/src.v2/app/models/index.ts
  Cooper/ClientApp/src.v2/app/models/user.ts
  Cooper/ClientApp/src.v2/app/services/index.ts
  Cooper/ClientApp/src.v2/app/services/session.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/session.service.ts
  Cooper/ClientApp/src.v2/app/services/user.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/user.service.ts
  Cooper/ClientApp/src.v2/app/services/users-interaction.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/users-interaction.service.ts
  Tools/MediaServer/MediaServer/MediaServer/Controllers/ImageController.cs
  Tools/MediaServer/MediaServer/MediaServer/MediaServer.csproj
  Tools/MediaServer/MediaServer/MediaServer/Startup.cs
Labels: front-end, refactoring

#164 Post-method for user (issue #154)
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.ts
  Cooper/ClientApp/src.v2/app/services/session.service.ts
  Cooper/ClientApp/src.v2/app/services/user.service.ts
Labels: bug, front-end

#167 Home page component
  Cooper/ClientApp/src.v2/app/app-routing.module.ts
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/components/index.ts
  Cooper/ClientApp/src.v2/app/layouts/home/home.layout.html
  Cooper/ClientApp/src.v2/app/layouts/home/home.layout.scss
  Cooper/ClientApp/src.v2/app/layouts/home/home.layout.spec.ts
  Cooper/ClientApp/src.v2/app/layouts/home/home.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/index.ts
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.html
Labels: enhancement, front-end

#174 Nickname on avatar card (#173)
  Cooper/ClientApp/src.v2/app/components/avatar-card/avatar-card.component.scss
  Cooper/ClientApp/src.v2/app/components/games-list/games-list.component.css
  Cooper/ClientApp/src.v2/app/components/user-connections-list/user-connections-list.component.css
Labels: 3 minutes task, bug, front-end

#177 [refactoring] Moving interceptor and adding header in its function (#168)
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/services/index.ts
  Cooper/ClientApp/src.v2/app/services/interceptor/cooper.interceptor.ts
  Cooper/ClientApp/src.v2/assets/cooper.interceptor.ts
  Cooper/ClientApp/tsconfig.json
Labels: 3 minutes task, refactoring

#178 Add linter
  Cooper/ClientApp/package.json
  Cooper/ClientApp/src.v2/app/app.component.spec.ts
  Cooper/ClientApp/src.v2/app/app.component.ts
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/components/avatar-card/avatar-card.component.ts
  Cooper/ClientApp/src.v2/app/components/game-card/game-card.component.ts
  Cooper/ClientApp/src.v2/app/components/game-list-item/game-list-item.component.ts
  Cooper/ClientApp/src.v2/app/components/games-list/games-list.component.ts
  Cooper/ClientApp/src.v2/app/components/login-form/login-form.component.ts
  Cooper/ClientApp/src.v2/app/components/my-profile/my-profile.component.ts
  Cooper/ClientApp/src.v2/app/components/navigation/navigation.component.ts
  Cooper/ClientApp/src.v2/app/components/poster/poster.component.ts
  Cooper/ClientApp/src.v2/app/components/registration-form/registration-form.component.ts
  Cooper/ClientApp/src.v2/app/components/user-connections-list/user-connections-list.component.ts
  Cooper/ClientApp/src.v2/app/components/user-info/user-info.component.ts
  Cooper/ClientApp/src.v2/app/enums/GameListTabs.ts
  Cooper/ClientApp/src.v2/app/guards/auth-guard.ts
  Cooper/ClientApp/src.v2/app/helpers/animation.helper.ts
  Cooper/ClientApp/src.v2/app/helpers/index.ts
  Cooper/ClientApp/src.v2/app/layouts/game/game.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/home/home.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/login/login.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/page-not-found/page-not-found.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/platform/platform.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/registration/registration.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.ts
  Cooper/ClientApp/src.v2/app/models/coop-navbar-item.ts
  Cooper/ClientApp/src.v2/app/models/game-model.ts
  Cooper/ClientApp/src.v2/app/models/user.ts
  Cooper/ClientApp/src.v2/app/services/authentification/authentification.service.ts
  Cooper/ClientApp/src.v2/app/services/games.service.ts
  Cooper/ClientApp/src.v2/app/services/session.service.ts
  Cooper/ClientApp/src.v2/app/services/user.service.ts
  Cooper/ClientApp/src.v2/app/services/users-interaction.service.ts
  Cooper/ClientApp/src.v2/assets/cooper.interceptor.ts
  Cooper/ClientApp/src.v2/environments/environment.ts
  Cooper/ClientApp/src.v2/main.ts
  Cooper/ClientApp/src.v2/polyfills.ts
  Cooper/ClientApp/tsconfig.json
  Cooper/ClientApp/tslint.json
Labels: feature, low

#176 Naming problems handled (#169)
  Cooper.Controllers/UsersConnectionController.cs
  Cooper/ClientApp/package-lock.json
  Cooper/ClientApp/package.json
  Cooper/ClientApp/src.v2/app/layouts/profile/profile.layout.ts
  Cooper/ClientApp/src.v2/app/services/index.ts
  Cooper/ClientApp/src.v2/app/services/users-interaction.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/users-social-connection.service.spec.ts
  Cooper/ClientApp/src.v2/app/services/users-social-connections.service.ts
Labels: 3 minutes task, refactoring

#183 Add git hook on pre-push
  .githooks/pre-push
  Cooper/ClientApp/package.json
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.ts
  Cooper/ClientApp/src.v2/app/services/interceptor/cooper.interceptor.ts
Labels: feature, low, technical

#182 #181 Add games component
  Cooper.Controllers/GameController.cs
  Cooper.DAO/GameDAO.cs
  Cooper.DAO/Interfaces/IDAO.cs
  Cooper.DAO/Interfaces/IGameDAO.cs
  Cooper.Repositories/GameRepository.cs
  Cooper.Repositories/Interfaces/IRepository.cs
  Cooper.Repositories/User/UserRepository.cs
  Cooper/ClientApp/package-lock.json
  Cooper/ClientApp/package.json
  Cooper/ClientApp/src.v2/app/app-routing.module.ts
  Cooper/ClientApp/src.v2/app/app.module.ts
  Cooper/ClientApp/src.v2/app/components/avatar-card/avatar-card.component.scss
  Cooper/ClientApp/src.v2/app/components/game-card/game-card.component.html
  Cooper/ClientApp/src.v2/app/components/game-list-item/game-list-item.component.html
  Cooper/ClientApp/src.v2/app/components/games-list/games-list.component.ts
  Cooper/ClientApp/src.v2/app/layouts/game/game.layout.css
  Cooper/ClientApp/src.v2/app/layouts/game/game.layout.html
  Cooper/ClientApp/src.v2/app/layouts/game/game.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/games/games.layout.ts
  Cooper/ClientApp/src.v2/app/layouts/top-panel/top-panel.layout.ts
  Cooper/ClientApp/src.v2/app/models/game-model.ts
  Cooper/ClientApp/src.v2/app/pipes/index.ts
  Cooper/ClientApp/src.v2/app/pipes/safe.pipe.ts
  Cooper/ClientApp/src.v2/app/services/games.service.ts
  Cooper/ClientApp/tsconfig.json
  Documentation/Database/UpdateScripts/add_tanks_islands_v0.0.1.sql
Labels: back-end, front-end

#190 #189 UPDATE CRUD refactoring
  Cooper.DAO/ChatDAO.cs
  Cooper.DAO/GameDAO.cs
  Cooper.DAO/GameReviewDAO.cs
  Cooper.DAO/GameStatisticsDAO.cs
  Cooper.DAO/MessageDAO.cs
  Cooper.DAO/UserDAO/UserDAO.cs
  Cooper.DAO/UserReviewDAO.cs
  Cooper.ORM/CRUD.cs
  Cooper.ORM/DbTools.cs
  Cooper.ORM/ICRUD.cs
  Cooper.Tests/ORM/DbToolsTest.cs
Labels: back-end
